### ISSUE TITLE
error when running forked and cloned sign-pledge.sh

### ISSUE THREAD

**Issue by bhaugen** [berneout/berneout-pledge#3]
I am sure I misunderstood something.
I forked https://github.com/berneout/berneout-pledge to https://github.com/bhaugen/berneout-pledge
Then cloned https://github.com/bhaugen/berneout-pledge to my computer.
Then from the berneout-pledge directory, did `./sign-pledge.sh`

Got this response:

```
This is not an official edition of The Berneout Pledge!  Please visit
https://github.com/berneout/berneout-pledge for the latest edition!
```

What did I do wrong?

**Comment by squeek502** [comment]
You  might not have fetched the tags. The script checks that HEAD is tagged.
