### ISSUE TITLE
Question on the pledge's viability if deleted from the contributor's repository

### ISSUE THREAD

**Issue by jleclanche** [berneout/berneout-pledge#4]
@kemitchell I just finished reading your fantastic article on the MIT license as well as [all the comments](https://github.com/berneout/berneout-pledge/issues/4), and I saw the mention about the pledge. I find it extremely promising.

Question on the wording here:

> This pledge applies to all the contributions I offer, so long as I
> make this pledge available at: (user-owned repository)

What does this mean for previous contributions, if the contributor decides to take the pledge down, or delete their github account? 

The intuitive thing is to have one pledge per organization and store the signed pledges in git, but that means losing a little scaling nicety of the pledge. More importantly, commits can easily be faked. This can be remedied by asking users to gpg-sign their commits, but now we're back to a system even more daunting than CLAs.

**Comment by kemitchell** [comment]
I expected individual users to post the pledge to their own accounts, passing through GitHub's (or whatever host's) auth.  Projects concerned with recordkeeping could automatically archive copies of pledges as they do their checks, on a per-patch basis.  The same automated tool could verify that each would-be contributor has a current, valid pledge online at the time they send each successive patch.
